on:
  push:
    branches:
      - master
jobs:
  deploy:
    name: dev-deploy
    environment: Actions Secrets
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3 # This action checks out for the latest code/branch that triggered this job

    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
 
    - name: Create layers
      run: |
        pip install --upgrade pip
        ls # Checking the files in current dir
        mkdir -p fastApi/python/ # Creating new directory for layer.
        pip install --target ./fastApi/python/  fastapi
        pip install --target ./fastApi/python/  mangum
        pip install --target ./fastApi/python/  google-auth
        pip install --target ./fastApi/python/  google-auth-oauthlib
        pip install --target ./fastApi/python/  google-auth-httplib2
        pip install --target ./fastApi/python/  pydantic
 
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.0

    - name: Terraform Init
      run: terraform init

    - name: Terraform Validate
      run: terraform validate

    - name: Terraform Plan
      run: terraform plan

    - name: Terraform Apply
      run: terraform apply -auto-approve
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}